### ISSUE TITLE
How to change scrub's height?

### ISSUE THREAD

**Issue by vnvyvu** [nick-michael/react-scrubber#42]
Scrubber is amazing. Thank you!

How can I change scrub's height (size)?

**Comment by nick-michael** [comment]
The bar itself has a class applied `bar` so you should be able to just add a height to that class styling.

There are some examples in the docs page:
https://nick-michael.github.io/react-scrubber/

At the bottom it shows the class names of each component so you can know where to apply styles. If you inspect that element you can see that `.bar` has been given an override height of `40px`

**Comment by nick-michael** [comment]
Closing as resolved
